// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: catalog/v1/catalog.proto

package catalog_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenreId       int32                  `protobuf:"varint,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`      // GenreID   int
	GenreName     string                 `protobuf:"bytes,2,opt,name=genre_name,json=genreName,proto3" json:"genre_name,omitempty"` // GenreName string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Genre) GetGenreId() int32 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *Genre) GetGenreName() string {
	if x != nil {
		return x.GenreName
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"` // AuthorID int → string (user_id из JWT)
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                         // Text     string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Review) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Review) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Ranking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankingValue  int32                  `protobuf:"varint,1,opt,name=ranking_value,json=rankingValue,proto3" json:"ranking_value,omitempty"` // RankingValue int
	RankingName   string                 `protobuf:"bytes,2,opt,name=ranking_name,json=rankingName,proto3" json:"ranking_name,omitempty"`     // RankingName  string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ranking) Reset() {
	*x = Ranking{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ranking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking) ProtoMessage() {}

func (x *Ranking) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking.ProtoReflect.Descriptor instead.
func (*Ranking) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Ranking) GetRankingValue() int32 {
	if x != nil {
		return x.RankingValue
	}
	return 0
}

func (x *Ranking) GetRankingName() string {
	if x != nil {
		return x.RankingName
	}
	return ""
}

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // bson.ObjectID → string hex
	ImdbId        string                 `protobuf:"bytes,2,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`             // ImdbID     string
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                             // Title      string
	PosterPath    string                 `protobuf:"bytes,4,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"` // PosterPath string
	YoutubeId     string                 `protobuf:"bytes,5,opt,name=youtube_id,json=youtubeId,proto3" json:"youtube_id,omitempty"`    // YouTubeID  string
	Genre         []*Genre               `protobuf:"bytes,6,rep,name=genre,proto3" json:"genre,omitempty"`                             // Genre      []Genre
	Reviews       []*Review              `protobuf:"bytes,7,rep,name=reviews,proto3" json:"reviews,omitempty"`                         // Review     []Review
	Ranking       *Ranking               `protobuf:"bytes,8,opt,name=ranking,proto3" json:"ranking,omitempty"`                         // Ranking    Ranking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *Movie) GetYoutubeId() string {
	if x != nil {
		return x.YoutubeId
	}
	return ""
}

func (x *Movie) GetGenre() []*Genre {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *Movie) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *Movie) GetRanking() *Ranking {
	if x != nil {
		return x.Ranking
	}
	return nil
}

type GetMoviesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// фильтры — расширяй по мере роста
	GenreNames    []string `protobuf:"bytes,1,rep,name=genre_names,json=genreNames,proto3" json:"genre_names,omitempty"` // фильтр по жанрам
	Page          int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                              // пагинация
	PageSize      int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesRequest) Reset() {
	*x = GetMoviesRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesRequest) ProtoMessage() {}

func (x *GetMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetMoviesRequest) GetGenreNames() []string {
	if x != nil {
		return x.GenreNames
	}
	return nil
}

func (x *GetMoviesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMoviesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesResponse) Reset() {
	*x = GetMoviesResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesResponse) ProtoMessage() {}

func (x *GetMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetMoviesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *GetMoviesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMovieByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImdbId        string                 `protobuf:"bytes,1,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"` // c.Param("imdb_id") из хэндлера
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIdRequest) Reset() {
	*x = GetMovieByIdRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdRequest) ProtoMessage() {}

func (x *GetMovieByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMovieByIdRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetMovieByIdRequest) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

type GetMovieByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIdResponse) Reset() {
	*x = GetMovieByIdResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdResponse) ProtoMessage() {}

func (x *GetMovieByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMovieByIdResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetMovieByIdResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type AddMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImdbId        string                 `protobuf:"bytes,1,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PosterPath    string                 `protobuf:"bytes,3,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	YoutubeId     string                 `protobuf:"bytes,4,opt,name=youtube_id,json=youtubeId,proto3" json:"youtube_id,omitempty"`
	Genre         []*Genre               `protobuf:"bytes,5,rep,name=genre,proto3" json:"genre,omitempty"`
	Ranking       *Ranking               `protobuf:"bytes,6,opt,name=ranking,proto3" json:"ranking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMovieRequest) Reset() {
	*x = AddMovieRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieRequest) ProtoMessage() {}

func (x *AddMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieRequest.ProtoReflect.Descriptor instead.
func (*AddMovieRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *AddMovieRequest) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *AddMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddMovieRequest) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *AddMovieRequest) GetYoutubeId() string {
	if x != nil {
		return x.YoutubeId
	}
	return ""
}

func (x *AddMovieRequest) GetGenre() []*Genre {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *AddMovieRequest) GetRanking() *Ranking {
	if x != nil {
		return x.Ranking
	}
	return nil
}

type AddMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedId    string                 `protobuf:"bytes,1,opt,name=inserted_id,json=insertedId,proto3" json:"inserted_id,omitempty"` // mongo InsertedID → hex string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMovieResponse) Reset() {
	*x = AddMovieResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieResponse) ProtoMessage() {}

func (x *AddMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieResponse.ProtoReflect.Descriptor instead.
func (*AddMovieResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *AddMovieResponse) GetInsertedId() string {
	if x != nil {
		return x.InsertedId
	}
	return ""
}

type UpdateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImdbId        string                 `protobuf:"bytes,1,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`       // c.Param("imdb_id")
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"` // userId из JWT контекста
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                         // req.Review
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewRequest) Reset() {
	*x = UpdateReviewRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewRequest) ProtoMessage() {}

func (x *UpdateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewRequest.ProtoReflect.Descriptor instead.
func (*UpdateReviewRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateReviewRequest) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *UpdateReviewRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *UpdateReviewRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankingName   string                 `protobuf:"bytes,1,opt,name=ranking_name,json=rankingName,proto3" json:"ranking_name,omitempty"` // sentiment от LLM
	RankingValue  int32                  `protobuf:"varint,2,opt,name=ranking_value,json=rankingValue,proto3" json:"ranking_value,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewResponse) Reset() {
	*x = UpdateReviewResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewResponse) ProtoMessage() {}

func (x *UpdateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewResponse.ProtoReflect.Descriptor instead.
func (*UpdateReviewResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateReviewResponse) GetRankingName() string {
	if x != nil {
		return x.RankingName
	}
	return ""
}

func (x *UpdateReviewResponse) GetRankingValue() int32 {
	if x != nil {
		return x.RankingValue
	}
	return 0
}

func (x *UpdateReviewResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetRecommendedMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // для GetUsersFavouriteGenres внутри
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                // RECOMMENDED_MOVIE_LIMIT из .env
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedMoviesRequest) Reset() {
	*x = GetRecommendedMoviesRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedMoviesRequest) ProtoMessage() {}

func (x *GetRecommendedMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendedMoviesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecommendedMoviesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendedMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecommendedMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedMoviesResponse) Reset() {
	*x = GetRecommendedMoviesResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedMoviesResponse) ProtoMessage() {}

func (x *GetRecommendedMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendedMoviesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *GetRecommendedMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type GetGenresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenresRequest) Reset() {
	*x = GetGenresRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenresRequest) ProtoMessage() {}

func (x *GetGenresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenresRequest.ProtoReflect.Descriptor instead.
func (*GetGenresRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{14}
}

type GetGenresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []*Genre               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenresResponse) Reset() {
	*x = GetGenresResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenresResponse) ProtoMessage() {}

func (x *GetGenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenresResponse.ProtoReflect.Descriptor instead.
func (*GetGenresResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *GetGenresResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                                   // в копейках
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                              // RUB
	DurationDays  int32                  `protobuf:"varint,5,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"` // 30 / 365
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *Plan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plan) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Plan) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *Plan) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *GetPlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type GetPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanResponse) Reset() {
	*x = GetPlanResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanResponse) ProtoMessage() {}

func (x *GetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanResponse.ProtoReflect.Descriptor instead.
func (*GetPlanResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlanResponse) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type ListPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlyActive    bool                   `protobuf:"varint,1,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *ListPlansRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

type ListPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *ListPlansResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"A\n" +
	"\x05Genre\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\x05R\agenreId\x12\x1d\n" +
	"\n" +
	"genre_name\x18\x02 \x01(\tR\tgenreName\"9\n" +
	"\x06Review\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"Q\n" +
	"\aRanking\x12#\n" +
	"\rranking_value\x18\x01 \x01(\x05R\frankingValue\x12!\n" +
	"\franking_name\x18\x02 \x01(\tR\vrankingName\"\x8c\x02\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aimdb_id\x18\x02 \x01(\tR\x06imdbId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vposter_path\x18\x04 \x01(\tR\n" +
	"posterPath\x12\x1d\n" +
	"\n" +
	"youtube_id\x18\x05 \x01(\tR\tyoutubeId\x12'\n" +
	"\x05genre\x18\x06 \x03(\v2\x11.payment.v1.GenreR\x05genre\x12,\n" +
	"\areviews\x18\a \x03(\v2\x12.payment.v1.ReviewR\areviews\x12-\n" +
	"\aranking\x18\b \x01(\v2\x13.payment.v1.RankingR\aranking\"d\n" +
	"\x10GetMoviesRequest\x12\x1f\n" +
	"\vgenre_names\x18\x01 \x03(\tR\n" +
	"genreNames\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"T\n" +
	"\x11GetMoviesResponse\x12)\n" +
	"\x06movies\x18\x01 \x03(\v2\x11.payment.v1.MovieR\x06movies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\".\n" +
	"\x13GetMovieByIdRequest\x12\x17\n" +
	"\aimdb_id\x18\x01 \x01(\tR\x06imdbId\"?\n" +
	"\x14GetMovieByIdResponse\x12'\n" +
	"\x05movie\x18\x01 \x01(\v2\x11.payment.v1.MovieR\x05movie\"\xd8\x01\n" +
	"\x0fAddMovieRequest\x12\x17\n" +
	"\aimdb_id\x18\x01 \x01(\tR\x06imdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vposter_path\x18\x03 \x01(\tR\n" +
	"posterPath\x12\x1d\n" +
	"\n" +
	"youtube_id\x18\x04 \x01(\tR\tyoutubeId\x12'\n" +
	"\x05genre\x18\x05 \x03(\v2\x11.payment.v1.GenreR\x05genre\x12-\n" +
	"\aranking\x18\x06 \x01(\v2\x13.payment.v1.RankingR\aranking\"3\n" +
	"\x10AddMovieResponse\x12\x1f\n" +
	"\vinserted_id\x18\x01 \x01(\tR\n" +
	"insertedId\"_\n" +
	"\x13UpdateReviewRequest\x12\x17\n" +
	"\aimdb_id\x18\x01 \x01(\tR\x06imdbId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"r\n" +
	"\x14UpdateReviewResponse\x12!\n" +
	"\franking_name\x18\x01 \x01(\tR\vrankingName\x12#\n" +
	"\rranking_value\x18\x02 \x01(\x05R\frankingValue\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"L\n" +
	"\x1bGetRecommendedMoviesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"I\n" +
	"\x1cGetRecommendedMoviesResponse\x12)\n" +
	"\x06movies\x18\x01 \x03(\v2\x11.payment.v1.MovieR\x06movies\"\x12\n" +
	"\x10GetGenresRequest\">\n" +
	"\x11GetGenresResponse\x12)\n" +
	"\x06genres\x18\x01 \x03(\v2\x11.payment.v1.GenreR\x06genres\"\xa7\x01\n" +
	"\x04Plan\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12#\n" +
	"\rduration_days\x18\x05 \x01(\x05R\fdurationDays\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\")\n" +
	"\x0eGetPlanRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"7\n" +
	"\x0fGetPlanResponse\x12$\n" +
	"\x04plan\x18\x01 \x01(\v2\x10.payment.v1.PlanR\x04plan\"3\n" +
	"\x10ListPlansRequest\x12\x1f\n" +
	"\vonly_active\x18\x01 \x01(\bR\n" +
	"onlyActive\";\n" +
	"\x11ListPlansResponse\x12&\n" +
	"\x05plans\x18\x01 \x03(\v2\x10.payment.v1.PlanR\x05plans2\x8a\x05\n" +
	"\x0eCatalogService\x12H\n" +
	"\tGetMovies\x12\x1c.payment.v1.GetMoviesRequest\x1a\x1d.payment.v1.GetMoviesResponse\x12Q\n" +
	"\fGetMovieById\x12\x1f.payment.v1.GetMovieByIdRequest\x1a .payment.v1.GetMovieByIdResponse\x12E\n" +
	"\bAddMovie\x12\x1b.payment.v1.AddMovieRequest\x1a\x1c.payment.v1.AddMovieResponse\x12Q\n" +
	"\fUpdateReview\x12\x1f.payment.v1.UpdateReviewRequest\x1a .payment.v1.UpdateReviewResponse\x12i\n" +
	"\x14GetRecommendedMovies\x12'.payment.v1.GetRecommendedMoviesRequest\x1a(.payment.v1.GetRecommendedMoviesResponse\x12H\n" +
	"\tGetGenres\x12\x1c.payment.v1.GetGenresRequest\x1a\x1d.payment.v1.GetGenresResponse\x12B\n" +
	"\aGetPlan\x12\x1a.payment.v1.GetPlanRequest\x1a\x1b.payment.v1.GetPlanResponse\x12H\n" +
	"\tListPlans\x12\x1c.payment.v1.ListPlansRequest\x1a\x1d.payment.v1.ListPlansResponseBGZEgithub.com/LearLocker/streaming/grpc/pkg/proto/catalog/v1;catalog_v1;b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(*Genre)(nil),                        // 0: payment.v1.Genre
	(*Review)(nil),                       // 1: payment.v1.Review
	(*Ranking)(nil),                      // 2: payment.v1.Ranking
	(*Movie)(nil),                        // 3: payment.v1.Movie
	(*GetMoviesRequest)(nil),             // 4: payment.v1.GetMoviesRequest
	(*GetMoviesResponse)(nil),            // 5: payment.v1.GetMoviesResponse
	(*GetMovieByIdRequest)(nil),          // 6: payment.v1.GetMovieByIdRequest
	(*GetMovieByIdResponse)(nil),         // 7: payment.v1.GetMovieByIdResponse
	(*AddMovieRequest)(nil),              // 8: payment.v1.AddMovieRequest
	(*AddMovieResponse)(nil),             // 9: payment.v1.AddMovieResponse
	(*UpdateReviewRequest)(nil),          // 10: payment.v1.UpdateReviewRequest
	(*UpdateReviewResponse)(nil),         // 11: payment.v1.UpdateReviewResponse
	(*GetRecommendedMoviesRequest)(nil),  // 12: payment.v1.GetRecommendedMoviesRequest
	(*GetRecommendedMoviesResponse)(nil), // 13: payment.v1.GetRecommendedMoviesResponse
	(*GetGenresRequest)(nil),             // 14: payment.v1.GetGenresRequest
	(*GetGenresResponse)(nil),            // 15: payment.v1.GetGenresResponse
	(*Plan)(nil),                         // 16: payment.v1.Plan
	(*GetPlanRequest)(nil),               // 17: payment.v1.GetPlanRequest
	(*GetPlanResponse)(nil),              // 18: payment.v1.GetPlanResponse
	(*ListPlansRequest)(nil),             // 19: payment.v1.ListPlansRequest
	(*ListPlansResponse)(nil),            // 20: payment.v1.ListPlansResponse
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	0,  // 0: payment.v1.Movie.genre:type_name -> payment.v1.Genre
	1,  // 1: payment.v1.Movie.reviews:type_name -> payment.v1.Review
	2,  // 2: payment.v1.Movie.ranking:type_name -> payment.v1.Ranking
	3,  // 3: payment.v1.GetMoviesResponse.movies:type_name -> payment.v1.Movie
	3,  // 4: payment.v1.GetMovieByIdResponse.movie:type_name -> payment.v1.Movie
	0,  // 5: payment.v1.AddMovieRequest.genre:type_name -> payment.v1.Genre
	2,  // 6: payment.v1.AddMovieRequest.ranking:type_name -> payment.v1.Ranking
	3,  // 7: payment.v1.GetRecommendedMoviesResponse.movies:type_name -> payment.v1.Movie
	0,  // 8: payment.v1.GetGenresResponse.genres:type_name -> payment.v1.Genre
	16, // 9: payment.v1.GetPlanResponse.plan:type_name -> payment.v1.Plan
	16, // 10: payment.v1.ListPlansResponse.plans:type_name -> payment.v1.Plan
	4,  // 11: payment.v1.CatalogService.GetMovies:input_type -> payment.v1.GetMoviesRequest
	6,  // 12: payment.v1.CatalogService.GetMovieById:input_type -> payment.v1.GetMovieByIdRequest
	8,  // 13: payment.v1.CatalogService.AddMovie:input_type -> payment.v1.AddMovieRequest
	10, // 14: payment.v1.CatalogService.UpdateReview:input_type -> payment.v1.UpdateReviewRequest
	12, // 15: payment.v1.CatalogService.GetRecommendedMovies:input_type -> payment.v1.GetRecommendedMoviesRequest
	14, // 16: payment.v1.CatalogService.GetGenres:input_type -> payment.v1.GetGenresRequest
	17, // 17: payment.v1.CatalogService.GetPlan:input_type -> payment.v1.GetPlanRequest
	19, // 18: payment.v1.CatalogService.ListPlans:input_type -> payment.v1.ListPlansRequest
	5,  // 19: payment.v1.CatalogService.GetMovies:output_type -> payment.v1.GetMoviesResponse
	7,  // 20: payment.v1.CatalogService.GetMovieById:output_type -> payment.v1.GetMovieByIdResponse
	9,  // 21: payment.v1.CatalogService.AddMovie:output_type -> payment.v1.AddMovieResponse
	11, // 22: payment.v1.CatalogService.UpdateReview:output_type -> payment.v1.UpdateReviewResponse
	13, // 23: payment.v1.CatalogService.GetRecommendedMovies:output_type -> payment.v1.GetRecommendedMoviesResponse
	15, // 24: payment.v1.CatalogService.GetGenres:output_type -> payment.v1.GetGenresResponse
	18, // 25: payment.v1.CatalogService.GetPlan:output_type -> payment.v1.GetPlanResponse
	20, // 26: payment.v1.CatalogService.ListPlans:output_type -> payment.v1.ListPlansResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
