// Code generated by ogen, DO NOT EDIT.

package subscription_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelSubscriptionByUuidOperation OperationName = "CancelSubscriptionByUuid"
	CreateSubscriptionOperation       OperationName = "CreateSubscription"
	GetSubscriptionByUuidOperation    OperationName = "GetSubscriptionByUuid"
	PaySubscriptionByUuidOperation    OperationName = "PaySubscriptionByUuid"
)
