// Code generated by ogen, DO NOT EDIT.

package subscription_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelSubscriptionByUuid implements CancelSubscriptionByUuid operation.
	//
	// Cancel subscription.
	//
	// POST /api/v1/subscriptions/{uuid}/cancel
	CancelSubscriptionByUuid(ctx context.Context, params CancelSubscriptionByUuidParams) (CancelSubscriptionByUuidRes, error)
	// CreateSubscription implements CreateSubscription operation.
	//
	// Create subscription.
	//
	// POST /api/v1/subscriptions
	CreateSubscription(ctx context.Context, req *CreateSubscriptionRequest) (CreateSubscriptionRes, error)
	// GetSubscriptionByUuid implements GetSubscriptionByUuid operation.
	//
	// Get subscription data for a uuid.
	//
	// GET /api/v1/subscriptions/{uuid}
	GetSubscriptionByUuid(ctx context.Context, params GetSubscriptionByUuidParams) (GetSubscriptionByUuidRes, error)
	// PaySubscriptionByUuid implements PaySubscriptionByUuid operation.
	//
	// Pay subscription.
	//
	// POST /api/v1/subscriptions/{uuid}/pay
	PaySubscriptionByUuid(ctx context.Context, req *PaySubscriptionRequest, params PaySubscriptionByUuidParams) (PaySubscriptionByUuidRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
