// Code generated by ogen, DO NOT EDIT.
package subscription_v1

type CancelSubscriptionByUuidRes interface {
	cancelSubscriptionByUuidRes()
}

type CreateSubscriptionRes interface {
	createSubscriptionRes()
}

type GetSubscriptionByUuidRes interface {
	getSubscriptionByUuidRes()
}

type PaySubscriptionByUuidRes interface {
	paySubscriptionByUuidRes()
}
