// Code generated by ogen, DO NOT EDIT.

package subscription_v1

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) cancelSubscriptionByUuidRes() {}
func (*BadRequestError) createSubscriptionRes()       {}
func (*BadRequestError) getSubscriptionByUuidRes()    {}
func (*BadRequestError) paySubscriptionByUuidRes()    {}

// CancelSubscriptionByUuidNoContent is response for CancelSubscriptionByUuid operation.
type CancelSubscriptionByUuidNoContent struct{}

func (*CancelSubscriptionByUuidNoContent) cancelSubscriptionByUuidRes() {}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	// HTTP-код ошибки.
	Code OptString `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() OptString {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val OptString) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelSubscriptionByUuidRes() {}
func (*ConflictError) paySubscriptionByUuidRes()    {}

// Ref: #/components/schemas/create_subscription_request
type CreateSubscriptionRequest struct {
	PlanID        uuid.UUID     `json:"plan_id"`
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPlanID returns the value of PlanID.
func (s *CreateSubscriptionRequest) GetPlanID() uuid.UUID {
	return s.PlanID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *CreateSubscriptionRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPlanID sets the value of PlanID.
func (s *CreateSubscriptionRequest) SetPlanID(val uuid.UUID) {
	s.PlanID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *CreateSubscriptionRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) cancelSubscriptionByUuidRes() {}
func (*InternalServerError) createSubscriptionRes()       {}
func (*InternalServerError) getSubscriptionByUuidRes()    {}
func (*InternalServerError) paySubscriptionByUuidRes()    {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelSubscriptionByUuidRes() {}
func (*NotFoundError) createSubscriptionRes()       {}
func (*NotFoundError) getSubscriptionByUuidRes()    {}
func (*NotFoundError) paySubscriptionByUuidRes()    {}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentMethod returns new OptPaymentMethod with value set to v.
func NewOptPaymentMethod(v PaymentMethod) OptPaymentMethod {
	return OptPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentMethod is optional PaymentMethod.
type OptPaymentMethod struct {
	Value PaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentMethod was set.
func (o OptPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSubscriptionStatus returns new OptSubscriptionStatus with value set to v.
func NewOptSubscriptionStatus(v SubscriptionStatus) OptSubscriptionStatus {
	return OptSubscriptionStatus{
		Value: v,
		Set:   true,
	}
}

// OptSubscriptionStatus is optional SubscriptionStatus.
type OptSubscriptionStatus struct {
	Value SubscriptionStatus
	Set   bool
}

// IsSet returns true if OptSubscriptionStatus was set.
func (o OptSubscriptionStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSubscriptionStatus) Reset() {
	var v SubscriptionStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSubscriptionStatus) SetTo(v SubscriptionStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSubscriptionStatus) Get() (v SubscriptionStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSubscriptionStatus) Or(d SubscriptionStatus) SubscriptionStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/pay_subscription_request
type PaySubscriptionRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PaySubscriptionRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PaySubscriptionRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_subscription_response
type PaySubscriptionResponse struct {
	UUID          OptUUID               `json:"uuid"`
	Status        OptSubscriptionStatus `json:"status"`
	PaymentID     OptUUID               `json:"payment_id"`
	PaymentMethod OptPaymentMethod      `json:"payment_method"`
	ExpiresAt     OptDateTime           `json:"expires_at"`
}

// GetUUID returns the value of UUID.
func (s *PaySubscriptionResponse) GetUUID() OptUUID {
	return s.UUID
}

// GetStatus returns the value of Status.
func (s *PaySubscriptionResponse) GetStatus() OptSubscriptionStatus {
	return s.Status
}

// GetPaymentID returns the value of PaymentID.
func (s *PaySubscriptionResponse) GetPaymentID() OptUUID {
	return s.PaymentID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PaySubscriptionResponse) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *PaySubscriptionResponse) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// SetUUID sets the value of UUID.
func (s *PaySubscriptionResponse) SetUUID(val OptUUID) {
	s.UUID = val
}

// SetStatus sets the value of Status.
func (s *PaySubscriptionResponse) SetStatus(val OptSubscriptionStatus) {
	s.Status = val
}

// SetPaymentID sets the value of PaymentID.
func (s *PaySubscriptionResponse) SetPaymentID(val OptUUID) {
	s.PaymentID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PaySubscriptionResponse) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *PaySubscriptionResponse) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

func (*PaySubscriptionResponse) paySubscriptionByUuidRes() {}

// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodCARD   PaymentMethod = "CARD"
	PaymentMethodSBP    PaymentMethod = "SBP"
	PaymentMethodWALLET PaymentMethod = "WALLET"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodCARD,
		PaymentMethodSBP,
		PaymentMethodWALLET,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodCARD:
		return []byte(s), nil
	case PaymentMethodSBP:
		return []byte(s), nil
	case PaymentMethodWALLET:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodCARD:
		*s = PaymentMethodCARD
		return nil
	case PaymentMethodSBP:
		*s = PaymentMethodSBP
		return nil
	case PaymentMethodWALLET:
		*s = PaymentMethodWALLET
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/subscription
type Subscription struct {
	UUID     OptUUID               `json:"uuid"`
	Status   OptSubscriptionStatus `json:"status"`
	PlanID   OptString             `json:"plan_id"`
	PlanName OptString             `json:"plan_name"`
	// Стоимость в копейках, берётся из тарифа.
	Amount OptInt64 `json:"amount"`
	// Валюта, берётся из тарифа.
	Currency      OptString        `json:"currency"`
	PaymentMethod OptPaymentMethod `json:"payment_method"`
	// Заполняется после оплаты.
	ExpiresAt OptDateTime `json:"expires_at"`
}

// GetUUID returns the value of UUID.
func (s *Subscription) GetUUID() OptUUID {
	return s.UUID
}

// GetStatus returns the value of Status.
func (s *Subscription) GetStatus() OptSubscriptionStatus {
	return s.Status
}

// GetPlanID returns the value of PlanID.
func (s *Subscription) GetPlanID() OptString {
	return s.PlanID
}

// GetPlanName returns the value of PlanName.
func (s *Subscription) GetPlanName() OptString {
	return s.PlanName
}

// GetAmount returns the value of Amount.
func (s *Subscription) GetAmount() OptInt64 {
	return s.Amount
}

// GetCurrency returns the value of Currency.
func (s *Subscription) GetCurrency() OptString {
	return s.Currency
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Subscription) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Subscription) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// SetUUID sets the value of UUID.
func (s *Subscription) SetUUID(val OptUUID) {
	s.UUID = val
}

// SetStatus sets the value of Status.
func (s *Subscription) SetStatus(val OptSubscriptionStatus) {
	s.Status = val
}

// SetPlanID sets the value of PlanID.
func (s *Subscription) SetPlanID(val OptString) {
	s.PlanID = val
}

// SetPlanName sets the value of PlanName.
func (s *Subscription) SetPlanName(val OptString) {
	s.PlanName = val
}

// SetAmount sets the value of Amount.
func (s *Subscription) SetAmount(val OptInt64) {
	s.Amount = val
}

// SetCurrency sets the value of Currency.
func (s *Subscription) SetCurrency(val OptString) {
	s.Currency = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Subscription) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Subscription) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

func (*Subscription) createSubscriptionRes()    {}
func (*Subscription) getSubscriptionByUuidRes() {}

// Ref: #/components/schemas/subscription_status
type SubscriptionStatus string

const (
	SubscriptionStatusPENDING         SubscriptionStatus = "PENDING"
	SubscriptionStatusAWAITINGPAYMENT SubscriptionStatus = "AWAITING_PAYMENT"
	SubscriptionStatusACTIVE          SubscriptionStatus = "ACTIVE"
	SubscriptionStatusEXPIRED         SubscriptionStatus = "EXPIRED"
	SubscriptionStatusCANCELLED       SubscriptionStatus = "CANCELLED"
)

// AllValues returns all SubscriptionStatus values.
func (SubscriptionStatus) AllValues() []SubscriptionStatus {
	return []SubscriptionStatus{
		SubscriptionStatusPENDING,
		SubscriptionStatusAWAITINGPAYMENT,
		SubscriptionStatusACTIVE,
		SubscriptionStatusEXPIRED,
		SubscriptionStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SubscriptionStatus) MarshalText() ([]byte, error) {
	switch s {
	case SubscriptionStatusPENDING:
		return []byte(s), nil
	case SubscriptionStatusAWAITINGPAYMENT:
		return []byte(s), nil
	case SubscriptionStatusACTIVE:
		return []byte(s), nil
	case SubscriptionStatusEXPIRED:
		return []byte(s), nil
	case SubscriptionStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SubscriptionStatus) UnmarshalText(data []byte) error {
	switch SubscriptionStatus(data) {
	case SubscriptionStatusPENDING:
		*s = SubscriptionStatusPENDING
		return nil
	case SubscriptionStatusAWAITINGPAYMENT:
		*s = SubscriptionStatusAWAITINGPAYMENT
		return nil
	case SubscriptionStatusACTIVE:
		*s = SubscriptionStatusACTIVE
		return nil
	case SubscriptionStatusEXPIRED:
		*s = SubscriptionStatusEXPIRED
		return nil
	case SubscriptionStatusCANCELLED:
		*s = SubscriptionStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
