// Code generated by ogen, DO NOT EDIT.

package subscription_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelSubscriptionByUuid implements CancelSubscriptionByUuid operation.
//
// Cancel subscription.
//
// POST /api/v1/subscriptions/{uuid}/cancel
func (UnimplementedHandler) CancelSubscriptionByUuid(ctx context.Context, params CancelSubscriptionByUuidParams) (r CancelSubscriptionByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSubscription implements CreateSubscription operation.
//
// Create subscription.
//
// POST /api/v1/subscriptions
func (UnimplementedHandler) CreateSubscription(ctx context.Context, req *CreateSubscriptionRequest) (r CreateSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubscriptionByUuid implements GetSubscriptionByUuid operation.
//
// Get subscription data for a uuid.
//
// GET /api/v1/subscriptions/{uuid}
func (UnimplementedHandler) GetSubscriptionByUuid(ctx context.Context, params GetSubscriptionByUuidParams) (r GetSubscriptionByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PaySubscriptionByUuid implements PaySubscriptionByUuid operation.
//
// Pay subscription.
//
// POST /api/v1/subscriptions/{uuid}/pay
func (UnimplementedHandler) PaySubscriptionByUuid(ctx context.Context, req *PaySubscriptionRequest, params PaySubscriptionByUuidParams) (r PaySubscriptionByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
